
services:
  db:
    image: postgres:15
    container_name: ${DB_CONTAINER_NAME}
    environment:
      POSTGRES_DB: ${POSTGRES_DATABASE}
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data

  adminer:
    image: adminer:latest
    container_name: my_adminer
    ports:
      - "${ADMINER_PORT}:8080"
    restart: always

volumes:
  postgres_data: